trigger:
- master

pool:
  name: 'fyp_pool'

variables:
  buildConfiguration: 'Release'

steps:

- script: echo Hello World!
  displayName: 'Run a one-liner script'
- checkout: self
  fetchDepth: 0

- script: |
    echo This codespace hostname:
    echo ------------------------
    echo $HOSTNAME
  displayName: 'Run a multi-line script'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'fyp-sonar-key'
    scannerMode: 'MSBuild'
    projectKey: '21025478_mvc2'
    projectName: 'mvc2'
    extraProperties: sonar.exclusions=**/*.cshtml, **/*.cs, **/*.php, **/*.json, **/*.html


- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    projects: '/workspaces/mvc2/WebAppProj/mvc2.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'build dotnet'
  inputs:
    command: 'build'
    projects: '/workspaces/mvc2/WebAppProj/mvc2.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: PublishPipelineArtifact@1
  displayName: 'publish'
  inputs:
    targetPath: $(build.artifactStagingDirectory)
    artifact: 'drop'
    publishLocation: 'pipeline'

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: 'test'
    projects: '/workspaces/mvc2/WebAppProj/mvc2.csproj'
    arguments: '--collect "Code Coverage"'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)/drop'

- task: WhiteSource@21
  displayName: 'Run Mend Bolt'
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'

#- task: WhiteSource@21
#  inputs:
#    cwd: '$(System.DefaultWorkingDirectory)'

#- task: Docker@2
#  inputs:
#    containerRegistry: 'Docker (don''t delete)'
#    repository: 'chloesacil / mvc2'
#    command: 'buildAndPush'
#    Dockerfile: '**/Dockerfile'